// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP IHWpaper_ddhf_order(SEXP sorted_pSEXP, SEXP filterorderSEXP, SEXP alphaSEXP);

R_CallMethodDef callMethods[]  = {
  {"C_IHWpaper_ddhf_order", (DL_FUNC) &IHWpaper_ddhf_order, 3},
  {NULL, NULL, 0}
};

void R_init_IHWpaper(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

