// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ddhf_order
Rcpp::IntegerVector ddhf_order(Rcpp::NumericVector sorted_p, Rcpp::IntegerVector filterorder, double alpha);
RcppExport SEXP _IHWpaper_ddhf_order(SEXP sorted_pSEXP, SEXP filterorderSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sorted_p(sorted_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type filterorder(filterorderSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddhf_order(sorted_p, filterorder, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IHWpaper_ddhf_order", (DL_FUNC) &_IHWpaper_ddhf_order, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_IHWpaper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
