// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ddhf_order
Rcpp::IntegerVector ddhf_order(Rcpp::NumericVector sorted_p, Rcpp::IntegerVector filterorder, double alpha);
RcppExport SEXP ihwPaper_ddhf_order(SEXP sorted_pSEXP, SEXP filterorderSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sorted_p(sorted_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type filterorder(filterorderSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(ddhf_order(sorted_p, filterorder, alpha));
    return __result;
END_RCPP
}
