# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddhf_order <- function(sorted_p, filterorder, alpha) {
    .Call('ddhwPaper_ddhf_order', PACKAGE = 'ddhwPaper', sorted_p, filterorder, alpha)
}

